name: Build and deploy workflow

on:
  push:
    branches:
      - main

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: clone code
        uses: actions/checkout@v2
      - name: docker build
        run: docker build -t dalbezh/todolist-api:$GITHUB_REF_NAME-$GITHUB_RUN_ID .
      - name: docker login
        run: echo ${{ secrets.DOCKER_TOKEN }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
      - name: docker push
        run: docker push dalbezh/todolist-api:$GITHUB_REF_NAME-$GITHUB_RUN_ID
  deploy:
    runs-on: ubuntu-latest
    env:
      DEBUG: ${{env_workers.DEBUG}}
      SECRET_KEY: ${{secrets.SECRET_KEY}}
      POSTGRES_USER: ${{secrets.POSTGRES_USER}}
      POSTGRES_PASSWORD: ${{secrets.POSTGRES_PASSWORD}}
      POSTGRES_DB: ${{secrets.POSTGRES_DB}}
      DATABASE_URL: ${{secrets.DATABASE_URL}}
    needs: build_and_push
    steps:
      - name: print environment
        run: env
      - name: clone code
        uses: actions/checkout@v2
      - name: print directory content
        run: ls -al
      - name: render configs
        run: |
          mkdir deploy
          cat infra/docker-compose.ci.yaml | envsubst > deploy/docker-compose_todolist.yml
      - name: print compose file
        run: cat deploy/docker-compose_todolist.yml